---
userAccountInfo:
  fields: !!python/tuple [username, usermail, password]
userBaseInfo:
- name: prefix
  options:
  - {label: Mr, value: '0'}
  - {label: Mrs, value: '1'}
  - {label: Ms, value: '2'}
  prompt: 'Prefix :'
  type: radio
  validate: []
- name: firstname
  prompt: 'First Name :'
  type: text
  validate: []
- name: lastname
  prompt: 'Last Name :'
  type: text
  validate: []
- name: gender
  options:
  - {label: Male, value: '0'}
  - {label: Female, value: '1'}
  prompt: 'Gender :'
  type: radio
  validate: []
- name: organization
  prompt: 'Organization :'
  type: textarea
  validate: []
- name: phone
  prompt: 'Phone :'
  type: text
  validate: []
- name: fax
  prompt: 'Fax :'
  type: text
  validate: []
- name: aperson
  options:
  - {label: '0', value: '0'}
  - {label: '1', value: '1'}
  - {label: '2', value: '2'}
  prompt: 'Accompany Person :'
  type: select
  validate: []
- name: address
  prompt: 'Address :'
  type: text
  validate: []
- name: city
  prompt: 'City :'
  type: text
  validate: []
- name: country
  prompt: 'Country :'
  type: text
  validate: []
- name: postcode
  prompt: 'Postal Code :'
  type: text
  validate: []
